#!/usr/bin/env bash
#
# Script name: dm-setbg
# Description: A wallpaper setting utility using dmenu, imv and swaybg/xwallpaper
# Dependencies: dmenu, xwallpaper

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

setbg_dir="${HOME}/.local/share/wallpapers"

yes_no() {
  echo $(printf "No|Yes" | rofi -sep '|' -dmenu -p "$1: ")
}

# Set wallpaper using either xwallpaper or swaybf
setbg() {
  case "$XDG_SESSION_TYPE" in
  'x11') feh --bg-scale "$1" ;;
  'wayland') swaybg -m "stretch" -i "$1" ;;
  *) notify-send "dm-setbg" "Unknown display server: $XDG_SESSION_TYPE" ;;
  esac
}

main() {
  category="$(printf "City|Landscape|Nature|Abstract|Japan" | rofi -sep '|' -dmenu -p "Category to choice from?")"
  category=$(echo "$category" | tr [A-Z] [a-z])

  choice="$(printf "Set|Random|Exit" | rofi -sep '|' -dmenu -p "What would you like to do?")"
  case "$choice" in
  "Set")
    # shellcheck disable=SC2154
    wallpaper="$(sxiv -tf -o "${setbg_dir}/${category}/")"
    echo "$wallpaper" >"$XDG_CACHE_HOME/wall"
    setbg "$wallpaper"
    notify-send "dm-setbg" "Wallpaper changed: $(basename "$wallpaper")."
    ;;

  "Random")
    valid_paper="No"
    until [ "$valid_paper" = "Yes" ]; do
      pidof "swaybg" && killall "swaybg"
      pidof "feh" && killall "feh"
      wallpaper="$(find "${setbg_dir}/${category}/" -type f | shuf -n 1)"
      setbg "$wallpaper" &
      echo "$wallpaper" >"$XDG_CACHE_HOME/wall"
      valid_paper=$(yes_no "Do you like the new wallpaper?" )
    done
    notify-send "dm-setbg" "Wallpaper changed: $(basename "$wallpaper")."
    ;;

  *) exit 1 ;;
  esac
}

# If script is run with NO argument, it will use 'dmenu'
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

# vim: ts=2 sts=2 sw=2 et
