# .toml only works for alacritty version >= 1.3
# for version < 1.3 use .yml 

[env]
TERM = xterm-256color

[window]
dynamic_padding = false
opacity = 0.95
title = "Alacritty"

[window.padding]
x = 0
y = 1 }

[window.class]
instance = "Alacritty"
general = "Alacritty"


[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = false

[[ keyboard.bindings ]]
action = SpawnNewInstance
key = Return
mods = Control|Shift

[terminal.shell]
program = "/bin/bash"

[colors]
draw_bold_text_with_bright_colors = true

import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

#[colors.primary]
#background = "#24273A" # base
#foreground = "#CAD3F5" # text
## Bright and dim foreground colors
#dim_foreground = "#CAD3F5" # text
#bright_foreground = "#CAD3F5" # text
#
#[colors.cursor]
#text = "#24273A" # base
#cursor = "#F4DBD6" # rosewater
#
#[vi_mode_cursor]
#text = "#24273A" # base
#cursor = "#B7BDF8" # lavender
#
#[colors.search.matches]
#foreground = "#24273A" # base
#background = "#A5ADCB" # subtext0
#[colors.search.focused_match]
#foreground = "#24273A" # base
#background = "#A6DA95" # green
#[colors.search.footer_bar]
#foreground = "#24273A" # base
#background = "#A5ADCB" # subtext0
#
#[colors.line_indicator]
#foreground = None
#background = None
#
#[colors.selection]
#text =       "#24273A" # base
#background = "#F4DBD6" # rosewater
#
#[colors.normal]
#black =   "#494D64" # surface1
#red =     "#ED8796" # red
#green =   "#A6DA95" # green
#yellow =  "#EED49F" # yellow
#blue =    "#8AADF4" # blue
#magenta = "#F5BDE6" # pink
#cyan =    "#8BD5CA" # teal
#white =   "#B8C0E0" # subtext1
#
#[colors.bright]
#black =   "#5B6078" # surface2
#red =     "#ED8796" # red
#green =   "#A6DA95" # green
#yellow =  "#EED49F" # yellow
#blue =    "#8AADF4" # blue
#magenta = "#F5BDE6" # pink
#cyan =    "#8BD5CA" # teal
#white =   "#A5ADCB" # subtext0
#
#[colors.dim]
#black =   "#494D64" # surface1
#red =     "#ED8796" # red
#green =   "#A6DA95" # green
#yellow =  "#EED49F" # yellow
#blue =    "#8AADF4" # blue
#magenta = "#F5BDE6" # pink
#cyan =    "#8BD5CA" # teal
#white =   "#B8C0E0" # subtext1

